# Generated by Django 4.1.3 on 2023-12-25 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_create_date_remove_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 1, 48, 1, 217719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 1, 48, 1, 217084, tzinfo=datetime.timezone.utc)),
        ),
    ]
